CREATE VIEW [DOSTEPNE_ID_OSOBY] AS
	SELECT MIN(ID_OSOBY) AS ID
	FROM OSOBA

CREATE VIEW [DOSTEPNE_ID_REJESTRATORA_MEDYCZNEGO] AS
	SELECT MAX(ID_REJESTRATORA) AS ID
	FROM REJESTRATOR_MEDYCZNY

CREATE VIEW [DOSTEPNE_ID_LEKARZA] AS
	SELECT MAX(ID_LEKARZA) AS ID
	FROM LEKARZ

CREATE VIEW [DOSTEPNE_ID_PACJENTA] AS
	SELECT MIN(ID_PACJENTA) AS ID
	FROM PACJENT